# Generated by Django 5.1.6 on 2025-08-03 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_alter_donation_status_receiverrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReceiverRequest',
        ),
    ]
