# Generated by Django 5.1.6 on 2025-08-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_delete_receiverrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('picked', 'Picked Up'), ('cancelled', 'Cancelled'), ('accepted_by_receiver', 'Accepted by Receiver'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
