# Generated by Django 5.1.6 on 2025-08-13 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0005_donation_receiver'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteered_donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('picked', 'Picked Up'), ('delivery_assigned', 'Delivery Assigned'), ('cancelled', 'Cancelled'), ('accepted_by_receiver', 'Accepted by Receiver'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
