# Generated by Django 5.1.6 on 2025-08-03 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_delete_receiverrequest'),
        ('receiver', '0003_alter_receiverrequest_receiver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiverrequest',
            old_name='requested_at',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='receiverrequest',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_requests', to='donor.donation'),
        ),
        migrations.AlterField(
            model_name='receiverrequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='requested', max_length=20),
        ),
    ]
