# Generated by Django 5.1.6 on 2025-08-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0004_rename_requested_at_receiverrequest_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiverrequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('received', 'Received')], default='requested', max_length=20),
        ),
    ]
