# Generated by Django 5.1.6 on 2025-08-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pickedup', 'Pickedup'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
