# Generated by Django 5.1.6 on 2025-08-03 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_delete_receiverrequest'),
        ('volunteer', '0002_alter_deliveryrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryrequest',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_requests', to='donor.donation'),
        ),
    ]
