# Generated by Django 5.1.6 on 2025-08-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0003_alter_deliveryrequest_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pickedup', 'Pickedup'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
