# Generated by Django 5.1.6 on 2025-08-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0004_alter_deliveryrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryrequest',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('pending', 'Pending'), ('pickedup', 'Pickedup'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
